departments:
- departmentsid: vgjr7kcqcf87
  name: Тест
  description: Это пробный раздел для улучшения системы и проведения тестов
  color: '#2b75ee'
  mentor_role: управляющий
  escalation: ''
- departmentsid: how5jhamq02m
  name: Вахтан
  description: ''
  color: '#f97316'
  mentor_role: ''
  escalation: ''
