departments:
- departmentsid: кодер
  name: кодер
  description: занимается кодом
  color: '#3b82f6'
- departmentsid: поиск
  name: поиск
  description: поиск информации
  color: '#929baa'
- departmentsid: советчик
  name: советчик
  description: участвует в переговорах
  color: '#bb3bf7'
