"""Kanban module — global task board for SynPin."""
from .service import KanbanService
from .models import (
    Task,
    TaskStatus,
    Priority,
    ActionType,
    HistoryEntry,
    TaskResult,
    WorkerAssignment,
    create_task,
    task_to_yaml,
    task_from_yaml,
    save_task,
    load_task,
    load_all_tasks,
)
from .config import (
    KanbanConfig,
    ColumnConfig,
    LabelConfig,
    WidgetConfig,
    load_config,
    save_config,
    get_columns,
    get_all_columns,
    get_labels,
    get_widget_config,
)

__all__ = [
    "KanbanService",
    "Task",
    "TaskStatus",
    "Priority",
    "ActionType",
    "HistoryEntry",
    "TaskResult",
    "WorkerAssignment",
    "create_task",
    "task_to_yaml",
    "task_from_yaml",
    "save_task",
    "load_task",
    "load_all_tasks",
    "KanbanConfig",
    "ColumnConfig",
    "LabelConfig",
    "WidgetConfig",
    "load_config",
    "save_config",
    "get_columns",
    "get_all_columns",
    "get_labels",
    "get_widget_config",
]
