- id: l7r8zs6i26wzyl
  label: TestPatch
  color: '#6b7280'
  order: 0
  enabled: true
- id: z6q3t0pkq1psu6
  label: TODO
  color: '#3b82f6'
  order: 1
  enabled: true
- id: n4dvlbbses8z85
  label: In Progress
  color: '#f97316'
  order: 2
  enabled: true
- id: t2vi3ub8iwt9gk
  label: Review
  color: '#f59e0b'
  order: 3
  enabled: true
- id: qxt2c7v4dbff5p
  label: Revision
  color: '#ef4444'
  order: 4
  enabled: true
- id: 424s3qetorrta2
  label: Blocked
  color: '#dc2626'
  order: 5
  enabled: true
- id: d5ihw5xspmqtqm
  label: Done
  color: '#22c55e'
  order: 6
  enabled: true
