- color: '#dc2626'
  description: ''
  enabled: true
  id: 424s3qetorrta2
  label: Blocked
  order: 0
  status: blocked
- color: '#6b7280'
  description: ''
  enabled: true
  id: p0gysg6mos5n3x
  label: Новая колонка
  order: 1
  status: todo
- color: '#f59e0b'
  description: ''
  enabled: true
  id: t2vi3ub8iwt9gk
  label: Review
  order: 2
  status: review
- color: '#f97316'
  description: ''
  enabled: true
  id: n4dvlbbses8z85
  label: In Progress
  order: 3
  status: in_progress
